'use client'

import * as React from 'react'
import { useState, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Checkbox } from '@/components/ui/checkbox'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { PageHeader } from '@/components/page-header'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  Plus,
  Clock,
  CheckCircle2,
  MoreHorizontal,
  Heart,
  AlertTriangle,
  CreditCard,
  User,
  Filter,
  Sparkles,
  Trash2,
  GripVertical,
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface Task {
  id: string
  title: string
  description?: string
  taskType: 'thank_you' | 'follow_up' | 'failed_payment' | 'card_expiring' | 'at_risk' | 'custom'
  donorName?: string
  dueDate?: string
  priority: 'low' | 'medium' | 'high'
  status: 'pending' | 'completed' | 'dismissed'
  autoGenerated: boolean
}

const INITIAL_TASKS: Task[] = [
  { id: 't1', title: 'Thank David Brown for first gift', description: 'Send a personal thank you for their $250 gift', taskType: 'thank_you', donorName: 'David Brown', dueDate: '2024-12-15', priority: 'high', status: 'pending', autoGenerated: true },
  { id: 't2', title: 'Welcome Amanda Lee', description: 'Reach out to new supporter Amanda', taskType: 'thank_you', donorName: 'Amanda Lee', dueDate: '2024-12-17', priority: 'high', status: 'pending', autoGenerated: true },
  { id: 't3', title: 'Follow up with Jennifer Davis', description: 'At-risk donor - no gift in 6 months', taskType: 'at_risk', donorName: 'Jennifer Davis', dueDate: '2024-12-20', priority: 'medium', status: 'pending', autoGenerated: true },
  { id: 't4', title: 'Rebecca card expiring soon', description: 'Card expires 6/2025 - remind to update', taskType: 'card_expiring', donorName: 'Rebecca Johnson', dueDate: '2025-05-01', priority: 'low', status: 'pending', autoGenerated: true },
  { id: 't5', title: 'Send December newsletter', description: 'Monthly update to all supporters', taskType: 'custom', dueDate: '2024-12-18', priority: 'medium', status: 'pending', autoGenerated: false },
  { id: 't6', title: 'Thank Thomas Smith', description: 'Sent thank you email', taskType: 'thank_you', donorName: 'Thomas Smith', priority: 'high', status: 'completed', autoGenerated: true },
]

const taskTypeConfig = {
  thank_you: { label: 'Thank You', icon: Heart, color: 'text-rose-600 bg-rose-50' },
  follow_up: { label: 'Follow Up', icon: User, color: 'text-blue-600 bg-blue-50' },
  failed_payment: { label: 'Failed Payment', icon: AlertTriangle, color: 'text-red-600 bg-red-50' },
  card_expiring: { label: 'Card Expiring', icon: CreditCard, color: 'text-amber-600 bg-amber-50' },
  at_risk: { label: 'At Risk', icon: AlertTriangle, color: 'text-orange-600 bg-orange-50' },
  custom: { label: 'Custom', icon: CheckCircle2, color: 'text-zinc-600 bg-zinc-100' },
}

const springTransition = {
  type: 'spring' as const,
  stiffness: 400,
  damping: 30,
}

const smoothTransition = {
  duration: 0.25,
  ease: [0.25, 0.1, 0.25, 1] as [number, number, number, number],
}

const staggerContainer = {
  animate: {
    transition: {
      staggerChildren: 0.05,
    },
  },
}

const fadeInUp = {
  initial: { opacity: 0, y: 12 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -8, transition: { duration: 0.2 } },
}

function CompletionConfetti() {
  const id = React.useId()
  return (
    <motion.div className="absolute inset-0 pointer-events-none overflow-hidden rounded-3xl">
      {Array.from({ length: 12 }).map((_, i) => (
        <motion.div
          key={`${id}-confetti-${i}`}
          initial={{ 
            opacity: 0,
            scale: 0,
            x: '50%',
            y: '50%',
          }}
          animate={{ 
            opacity: [0, 1, 0],
            scale: [0, 1, 0.5],
            x: `${50 + (Math.random() - 0.5) * 100}%`,
            y: `${50 + (Math.random() - 0.5) * 80}%`,
          }}
          transition={{
            duration: 0.8,
            ease: 'easeOut',
            delay: i * 0.02,
            times: [0, 0.3, 1],
          }}
          className="absolute w-2 h-2 rounded-full"
          style={{
            backgroundColor: ['#10b981', '#3b82f6', '#8b5cf6', '#f59e0b', '#ec4899'][i % 5],
          }}
        />
      ))}
    </motion.div>
  )
}

function TaskRow({ 
  task, 
  onToggle, 
  onDismiss,
  index 
}: { 
  task: Task
  onToggle: () => void
  onDismiss: () => void
  index: number 
}) {
  const [showConfetti, setShowConfetti] = useState(false)
  const [isHovered, setIsHovered] = useState(false)
  const typeConfig = taskTypeConfig[task.taskType]
  const Icon = typeConfig.icon
  const isOverdue = task.dueDate && new Date(task.dueDate) < new Date() && task.status === 'pending'
  const isDueToday = task.dueDate && new Date(task.dueDate).toDateString() === new Date().toDateString()

  const handleToggle = () => {
    if (task.status === 'pending') {
      setShowConfetti(true)
      setTimeout(() => setShowConfetti(false), 1000)
    }
    onToggle()
  }

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, x: -100 }}
      transition={{ ...smoothTransition, delay: index * 0.05 }}
      onHoverStart={() => setIsHovered(true)}
      onHoverEnd={() => setIsHovered(false)}
      className={cn(
        "relative group flex items-start gap-4 p-5 sm:p-6 border rounded-3xl transition-colors",
        task.status === 'completed' 
          ? "bg-muted/30 border-transparent" 
          : "bg-card border-border hover:border-muted-foreground/30"
      )}
      style={{
        boxShadow: isHovered && task.status !== 'completed' 
          ? '0 20px 40px -12px rgba(0,0,0,0.1)' 
          : 'none',
      }}
    >
      {showConfetti && <CompletionConfetti />}
      
      <motion.div 
        className="mt-1.5 relative"
        whileTap={{ scale: 0.9 }}
      >
        <Checkbox
          checked={task.status === 'completed'}
          onCheckedChange={handleToggle}
          className="h-5 w-5 rounded-md border-border data-[state=checked]:bg-primary data-[state=checked]:border-primary transition-all"
        />
          <AnimatePresence>
            {task.status === 'completed' && (
              <motion.div
                key={`check-${task.id}`}
                initial={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0, opacity: 0 }}
                transition={springTransition}
                className="absolute -top-1 -right-1 w-3 h-3 bg-emerald-500 rounded-full flex items-center justify-center"
              >
                <svg className="w-2 h-2 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={4}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </motion.div>
            )}
          </AnimatePresence>
      </motion.div>
      
      <motion.div 
        className={cn("flex h-10 w-10 sm:h-11 sm:w-11 items-center justify-center rounded-2xl shrink-0 shadow-sm", typeConfig.color)}
        whileHover={{ scale: 1.05, rotate: 3 }}
        whileTap={{ scale: 0.95 }}
        transition={springTransition}
      >
        <Icon className="h-4 w-4 sm:h-5 sm:w-5" />
      </motion.div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
          <motion.p 
            layout="position"
            className={cn(
              "font-bold text-sm tracking-tight text-foreground",
              task.status === 'completed' && "line-through text-muted-foreground"
            )}
          >
            {task.title}
          </motion.p>
            <AnimatePresence>
              {task.priority === 'high' && task.status !== 'completed' && (
                <motion.div
                  key={`priority-${task.id}`}
                  initial={{ scale: 0, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0, opacity: 0 }}
                  transition={springTransition}
                >
                  <Badge className="bg-rose-50 text-rose-600 border-0 text-[10px] font-black uppercase tracking-widest px-1.5 h-4">High</Badge>
                </motion.div>
              )}
              {task.autoGenerated && task.status !== 'completed' && (
                <motion.div
                  key={`auto-${task.id}`}
                  initial={{ scale: 0, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0, opacity: 0 }}
                  transition={{ ...springTransition, delay: 0.05 }}
                >
                  <Badge className="bg-indigo-50 text-indigo-600 border-0 text-[10px] font-black uppercase tracking-widest px-1.5 h-4 gap-1">
                    <Sparkles className="h-2.5 w-2.5" />
                    Auto
                  </Badge>
                </motion.div>
              )}
            </AnimatePresence>
        </div>
        <AnimatePresence>
          {task.description && task.status !== 'completed' && (
            <motion.p 
              key={`desc-${task.id}`}
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="text-xs font-medium text-muted-foreground mt-1 line-clamp-1"
            >
              {task.description}
            </motion.p>
          )}
        </AnimatePresence>
        <motion.div 
          layout
          className="flex items-center gap-2 sm:gap-4 mt-3 sm:mt-4 flex-wrap"
        >
            <AnimatePresence>
              {task.donorName && (
                <motion.div
                  key={`donor-${task.id}`}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  whileHover={{ scale: 1.02 }}
                  transition={springTransition}
                  className="flex items-center gap-2 px-2.5 py-1 rounded-full bg-muted border border-border/50"
                >
                  <User className="h-3 w-3 text-muted-foreground" />
                  <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">{task.donorName}</span>
                </motion.div>
              )}
              {task.dueDate && (
                <motion.div
                  key={`due-${task.id}`}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  whileHover={{ scale: 1.02 }}
                  transition={{ ...springTransition, delay: 0.02 }}
                  className={cn(
                    "flex items-center gap-2 px-2.5 py-1 rounded-full border",
                    isOverdue 
                      ? "bg-rose-50 border-rose-100 text-rose-700" 
                      : isDueToday 
                        ? "bg-amber-50 border-amber-100 text-amber-700" 
                        : "bg-muted border-border/50 text-muted-foreground"
                  )}
                >
                  <Clock className="h-3 w-3" />
                  <span className="text-[10px] font-bold uppercase tracking-wider">
                    {isOverdue ? 'Overdue' : isDueToday ? 'Due Today' : new Date(task.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                  </span>
                </motion.div>
              )}
            </AnimatePresence>
        </motion.div>
      </div>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
            <Button variant="ghost" size="icon" className="h-9 w-9 shrink-0 text-muted-foreground hover:text-foreground rounded-xl">
              <MoreHorizontal className="h-5 w-5" />
            </Button>
          </motion.div>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="rounded-2xl border-border p-2 shadow-xl min-w-[180px]">
          <DropdownMenuItem onClick={handleToggle} className="rounded-xl text-xs font-bold py-2.5 cursor-pointer">
            <CheckCircle2 className="mr-2 h-4 w-4 text-muted-foreground" />
            {task.status === 'completed' ? 'Mark Incomplete' : 'Mark Complete'}
          </DropdownMenuItem>
          {task.donorName && (
            <DropdownMenuItem className="rounded-xl text-xs font-bold py-2.5 cursor-pointer">
              <User className="mr-2 h-4 w-4 text-muted-foreground" />
              View Partner
            </DropdownMenuItem>
          )}
          <DropdownMenuItem 
            onClick={onDismiss}
            className="rounded-xl text-xs font-bold py-2.5 text-destructive focus:text-destructive focus:bg-destructive/10 cursor-pointer"
          >
            <Trash2 className="mr-2 h-4 w-4" />
            Dismiss Task
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: isHovered && task.status !== 'completed' ? 0.5 : 0 }}
        className="absolute left-2 top-1/2 -translate-y-1/2 cursor-grab active:cursor-grabbing hidden sm:block"
      >
        <GripVertical className="h-4 w-4 text-muted-foreground" />
      </motion.div>
    </motion.div>
  )
}

function EmptyState({ filter }: { filter: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={smoothTransition}
    >
      <Card className="border-border border-dashed bg-muted/20 rounded-[2.5rem]">
        <CardContent className="p-12 sm:p-24 text-center">
            <motion.div 
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ ...smoothTransition, delay: 0.1 }}
              className="h-16 w-16 sm:h-20 sm:w-20 rounded-3xl bg-card shadow-sm border border-border flex items-center justify-center mx-auto mb-6 sm:mb-8"
            >
              <motion.div
                animate={{ 
                  rotate: [0, 10, -10, 0],
                }}
                transition={{ 
                  duration: 2,
                  repeat: Infinity,
                  repeatDelay: 3,
                  ease: 'easeInOut',
                }}
              >
                <CheckCircle2 className="h-8 w-8 sm:h-10 sm:w-10 text-muted-foreground/30" />
              </motion.div>
            </motion.div>
          <motion.h3 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.15 }}
            className="font-black text-xl sm:text-2xl text-foreground tracking-tight"
          >
            All caught up!
          </motion.h3>
          <motion.p 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-2 text-sm font-medium text-muted-foreground max-w-[280px] mx-auto"
          >
            No {filter === 'all' ? '' : filter} tasks remaining. You're operating at peak efficiency.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25 }}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            <Button className="mt-8 sm:mt-10 h-11 sm:h-12 px-8 sm:px-10 rounded-2xl text-[10px] font-black uppercase tracking-[0.2em]">
              <Plus className="mr-2 h-4 w-4" />
              Create Task
            </Button>
          </motion.div>
        </CardContent>
      </Card>
    </motion.div>
  )
}

function StatCard({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <motion.div
      whileHover={{ scale: 1.02, y: -2 }}
      whileTap={{ scale: 0.98 }}
      transition={springTransition}
      className={cn(
        "flex items-center gap-3 px-4 py-3 rounded-2xl border transition-colors cursor-default",
        color
      )}
    >
      <motion.span 
        key={value}
        initial={{ scale: 1.2, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        className="text-2xl font-black tabular-nums"
      >
        {value}
      </motion.span>
      <span className="text-[10px] font-bold uppercase tracking-wider opacity-70">{label}</span>
    </motion.div>
  )
}

export default function TasksPage() {
  const [taskList, setTaskList] = useState<Task[]>(INITIAL_TASKS)
  const [filter, setFilter] = useState<'all' | 'pending' | 'completed'>('pending')

  const handleToggle = (id: string) => {
    setTaskList(prev => prev.map(t => 
      t.id === id ? { ...t, status: t.status === 'completed' ? 'pending' : 'completed' } : t
    ))
  }

  const handleDismiss = (id: string) => {
    setTaskList(prev => prev.filter(t => t.id !== id))
  }

  const handleClearCompleted = () => {
    setTaskList(prev => prev.filter(t => t.status !== 'completed'))
  }

  const filteredTasks = useMemo(() => {
    return taskList.filter(task => {
      if (task.status === 'dismissed') return false
      if (filter === 'pending' && task.status !== 'pending') return false
      if (filter === 'completed' && task.status !== 'completed') return false
      return true
    })
  }, [taskList, filter])

  const pendingCount = taskList.filter(t => t.status === 'pending').length
  const completedCount = taskList.filter(t => t.status === 'completed').length
  const overdueCount = taskList.filter(t => 
    t.status === 'pending' && t.dueDate && new Date(t.dueDate) < new Date()
  ).length

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3 }}
      className="space-y-6 pb-20"
    >
      <PageHeader 
        title="Tasks" 
        description="Stay on top of donor follow-ups and ministry administration."
      >
        <motion.div 
          className="flex items-center gap-2"
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
        >
          <AnimatePresence>
            {completedCount > 0 && (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
              >
                <Button
                  variant="outline"
                  size="sm"
                  className="h-9 px-4 text-xs font-medium"
                  onClick={handleClearCompleted}
                >
                  Clear Completed
                </Button>
              </motion.div>
            )}
          </AnimatePresence>
          <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
            <Button size="sm" className="h-9 px-4 text-xs font-medium">
              <Plus className="mr-2 h-4 w-4" />
              New Task
            </Button>
          </motion.div>
        </motion.div>
      </PageHeader>

      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="flex flex-wrap gap-3"
      >
        <StatCard 
          label="Pending" 
          value={pendingCount} 
          color="bg-amber-50 border-amber-100 text-amber-700"
        />
        <StatCard 
          label="Completed" 
          value={completedCount} 
          color="bg-emerald-50 border-emerald-100 text-emerald-700"
        />
        {overdueCount > 0 && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={springTransition}
          >
            <StatCard 
              label="Overdue" 
              value={overdueCount} 
              color="bg-rose-50 border-rose-100 text-rose-700"
            />
          </motion.div>
        )}
      </motion.div>

      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
        className="flex flex-col sm:flex-row items-center justify-between gap-4"
      >
        <Tabs value={filter} onValueChange={(v) => setFilter(v as 'all' | 'pending' | 'completed')} className="w-full sm:w-auto">
          <TabsList className="bg-muted/50 border border-border p-1.5 h-auto rounded-2xl w-full sm:w-auto">
            {(['all', 'pending', 'completed'] as const).map((tab) => (
              <TabsTrigger 
                key={tab}
                value={tab} 
                className="rounded-xl data-[state=active]:bg-card data-[state=active]:shadow-sm px-4 sm:px-6 py-2 text-[10px] font-black uppercase tracking-widest text-muted-foreground data-[state=active]:text-foreground transition-all"
              >
                <motion.span layout>
                  {tab === 'all' ? 'All' : tab === 'pending' ? `Pending (${pendingCount})` : `Completed (${completedCount})`}
                </motion.span>
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
        <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
          <Button variant="outline" size="sm" className="w-full sm:w-auto h-11 rounded-2xl border-border bg-card text-[10px] font-black uppercase tracking-widest text-muted-foreground hover:text-foreground">
            <Filter className="h-4 w-4 mr-2" />
            Filter & Sort
          </Button>
        </motion.div>
      </motion.div>

      <AnimatePresence mode="wait">
        {filteredTasks.length > 0 ? (
          <motion.div
            key={`task-list-${filter}`}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="space-y-4"
          >
            {filteredTasks.map((task, index) => (
              <TaskRow 
                key={task.id} 
                task={task} 
                onToggle={() => handleToggle(task.id)}
                onDismiss={() => handleDismiss(task.id)}
                index={index}
              />
            ))}
          </motion.div>
        ) : (
          <EmptyState key={`empty-state-${filter}`} filter={filter} />
        )}
      </AnimatePresence>
    </motion.div>
  )
}
