'use client'

import * as React from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Checkbox } from '@/components/ui/checkbox'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  Plus,
  Clock,
  CheckCircle2,
  MoreHorizontal,
  Heart,
  AlertTriangle,
  CreditCard,
  User,
  Filter,
  Sparkles,
  Check,
  ChevronRight,
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface Task {
  id: string
  title: string
  description?: string
  taskType: 'thank_you' | 'follow_up' | 'failed_payment' | 'card_expiring' | 'at_risk' | 'custom'
  donorName?: string
  dueDate?: string
  priority: 'low' | 'medium' | 'high'
  status: 'pending' | 'completed' | 'dismissed'
  autoGenerated: boolean
}

const INITIAL_TASKS: Task[] = [
  { id: 't1', title: 'Thank David Brown for first gift', description: 'Send a personal thank you for their $250 gift', taskType: 'thank_you', donorName: 'David Brown', dueDate: '2024-12-15', priority: 'high', status: 'pending', autoGenerated: true },
  { id: 't2', title: 'Welcome Amanda Lee', description: 'Reach out to new supporter Amanda', taskType: 'thank_you', donorName: 'Amanda Lee', dueDate: '2024-12-17', priority: 'high', status: 'pending', autoGenerated: true },
  { id: 't3', title: 'Follow up with Jennifer Davis', description: 'At-risk donor - no gift in 6 months', taskType: 'at_risk', donorName: 'Jennifer Davis', dueDate: '2024-12-20', priority: 'medium', status: 'pending', autoGenerated: true },
  { id: 't4', title: 'Rebecca card expiring soon', description: 'Card expires 6/2025 - remind to update', taskType: 'card_expiring', donorName: 'Rebecca Johnson', dueDate: '2025-05-01', priority: 'low', status: 'pending', autoGenerated: true },
  { id: 't5', title: 'Send December newsletter', description: 'Monthly update to all supporters', taskType: 'custom', dueDate: '2024-12-18', priority: 'medium', status: 'pending', autoGenerated: false },
  { id: 't6', title: 'Thank Thomas Smith', description: 'Sent thank you email', taskType: 'thank_you', donorName: 'Thomas Smith', priority: 'high', status: 'completed', autoGenerated: true },
]

const taskTypeConfig = {
  thank_you: { label: 'Thank You', icon: Heart, color: 'text-rose-600 bg-rose-50' },
  follow_up: { label: 'Follow Up', icon: User, color: 'text-blue-600 bg-blue-50' },
  failed_payment: { label: 'Failed Payment', icon: AlertTriangle, color: 'text-red-600 bg-red-50' },
  card_expiring: { label: 'Card Expiring', icon: CreditCard, color: 'text-amber-600 bg-amber-50' },
  at_risk: { label: 'At Risk', icon: AlertTriangle, color: 'text-orange-600 bg-orange-50' },
  custom: { label: 'Custom', icon: CheckCircle2, color: 'text-zinc-600 bg-zinc-100' },
}

function TaskRow({ task, onToggle }: { task: Task; onToggle: () => void }) {
  const typeConfig = taskTypeConfig[task.taskType]
  const Icon = typeConfig.icon
  const isOverdue = task.dueDate && new Date(task.dueDate) < new Date() && task.status === 'pending'
  const isDueToday = task.dueDate && new Date(task.dueDate).toDateString() === new Date().toDateString()

  return (
    <div className={cn(
      "group flex items-start gap-4 p-6 border rounded-3xl transition-all",
      task.status === 'completed' 
        ? "bg-zinc-50/50 border-transparent opacity-60" 
        : "bg-white border-zinc-200 hover:border-zinc-300 hover:shadow-xl hover:shadow-zinc-200/40"
    )}>
      <div className="mt-1.5">
        <Checkbox
          checked={task.status === 'completed'}
          onCheckedChange={() => onToggle()}
          className="h-5 w-5 rounded-md border-zinc-200 data-[state=checked]:bg-zinc-900 data-[state=checked]:border-zinc-900 transition-all"
        />
      </div>
      
      <div className={cn("flex h-11 w-11 items-center justify-center rounded-2xl shrink-0 shadow-sm", typeConfig.color)}>
        <Icon className="h-5 w-5" />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-3">
          <p className={cn(
            "font-bold text-sm tracking-tight text-zinc-900",
            task.status === 'completed' && "line-through text-zinc-400"
          )}>{task.title}</p>
          {task.priority === 'high' && (
            <Badge className="bg-rose-50 text-rose-600 border-0 text-[10px] font-black uppercase tracking-widest px-1.5 h-4">High</Badge>
          )}
        </div>
        {task.description && (
          <p className="text-xs font-medium text-zinc-500 mt-1 line-clamp-1">{task.description}</p>
        )}
        <div className="flex items-center gap-4 mt-4">
          {task.donorName && (
            <div className="flex items-center gap-2 px-2.5 py-1 rounded-full bg-zinc-100 border border-zinc-200/50">
              <User className="h-3 w-3 text-zinc-400" />
              <span className="text-[10px] font-bold text-zinc-600 uppercase tracking-wider">{task.donorName}</span>
            </div>
          )}
          {task.dueDate && (
            <div className={cn(
              "flex items-center gap-2 px-2.5 py-1 rounded-full border",
              isOverdue 
                ? "bg-rose-50 border-rose-100 text-rose-700" 
                : isDueToday 
                  ? "bg-amber-50 border-amber-100 text-amber-700" 
                  : "bg-zinc-50 border-zinc-100 text-zinc-500"
            )}>
              <Clock className="h-3 w-3" />
              <span className="text-[10px] font-bold uppercase tracking-wider">
                {isOverdue ? 'Overdue' : isDueToday ? 'Due Today' : new Date(task.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
              </span>
            </div>
          )}
        </div>
      </div>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" size="icon" className="h-9 w-9 shrink-0 text-zinc-400 hover:text-zinc-900 rounded-xl">
            <MoreHorizontal className="h-5 w-5" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="rounded-2xl border-zinc-100 p-2 shadow-xl">
          <DropdownMenuItem onClick={onToggle} className="rounded-xl text-xs font-bold py-2.5">
            <CheckCircle2 className="mr-2 h-4 w-4 text-zinc-400" />
            {task.status === 'completed' ? 'Mark Incomplete' : 'Mark Complete'}
          </DropdownMenuItem>
          {task.donorName && (
            <DropdownMenuItem className="rounded-xl text-xs font-bold py-2.5">
              <User className="mr-2 h-4 w-4 text-zinc-400" />
              View Partner
            </DropdownMenuItem>
          )}
          <DropdownMenuItem className="rounded-xl text-xs font-bold py-2.5 text-rose-600 focus:text-rose-700 focus:bg-rose-50">
            Dismiss Task
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

export default function TasksPage() {
  const [taskList, setTaskList] = React.useState<Task[]>(INITIAL_TASKS)
  const [filter, setFilter] = React.useState<'all' | 'pending' | 'completed'>('pending')

  const handleToggle = (id: string) => {
    setTaskList(prev => prev.map(t => 
      t.id === id ? { ...t, status: t.status === 'completed' ? 'pending' : 'completed' } : t
    ))
  }

  const filteredTasks = taskList.filter(task => {
    if (task.status === 'dismissed') return false
    if (filter === 'pending' && task.status !== 'pending') return false
    if (filter === 'completed' && task.status !== 'completed') return false
    return true
  })

  const pendingCount = taskList.filter(t => t.status === 'pending').length
  const completedCount = taskList.filter(t => t.status === 'completed').length

  return (
    <div className="min-h-full space-y-10">
      <div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between">
        <div>
          <h1 className="text-4xl font-black tracking-tighter text-zinc-900 lg:text-5xl">Tasks</h1>
          <p className="mt-2 text-sm font-medium text-zinc-500 leading-relaxed">Stay on top of donor follow-ups and ministry administration.</p>
        </div>
        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            size="sm"
            className="h-11 rounded-2xl border-zinc-200 px-6 text-xs font-bold text-zinc-600 hover:text-zinc-900 shadow-sm uppercase tracking-widest"
            onClick={() => setTaskList(prev => prev.filter(t => t.status !== 'completed'))}
          >
            Clear Completed
          </Button>
          <Button
            size="sm"
            className="h-11 gap-3 bg-zinc-900 rounded-2xl px-6 text-xs font-bold text-white hover:bg-zinc-800 shadow-xl shadow-zinc-200/50 uppercase tracking-widest"
          >
            <Plus className="size-4" />
            New Task
          </Button>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
        <Tabs value={filter} onValueChange={(v) => setFilter(v as any)} className="w-full sm:w-auto">
          <TabsList className="bg-zinc-100/50 border border-zinc-100 p-1.5 h-auto rounded-2xl w-full sm:w-auto">
            <TabsTrigger value="all" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm px-6 py-2 text-[10px] font-black uppercase tracking-widest text-zinc-400 data-[state=active]:text-zinc-900 transition-all">All</TabsTrigger>
            <TabsTrigger value="pending" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm px-6 py-2 text-[10px] font-black uppercase tracking-widest text-zinc-400 data-[state=active]:text-zinc-900 transition-all">
              Pending ({pendingCount})
            </TabsTrigger>
            <TabsTrigger value="completed" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm px-6 py-2 text-[10px] font-black uppercase tracking-widest text-zinc-400 data-[state=active]:text-zinc-900 transition-all">
              Completed ({completedCount})
            </TabsTrigger>
          </TabsList>
        </Tabs>
        <Button variant="outline" size="sm" className="w-full sm:w-auto h-11 rounded-2xl border-zinc-200 bg-white text-[10px] font-black uppercase tracking-widest text-zinc-500 hover:text-zinc-900">
          <Filter className="h-4 w-4 mr-2" />
          Filter & Sort
        </Button>
      </div>

      <div className="space-y-4">
        {filteredTasks.length > 0 ? (
          filteredTasks.map(task => (
            <TaskRow 
              key={task.id} 
              task={task} 
              onToggle={() => handleToggle(task.id)}
            />
          ))
        ) : (
          <Card className="border-zinc-200 border-dashed bg-zinc-50/30 rounded-[2.5rem]">
            <CardContent className="p-24 text-center">
              <div className="h-20 w-20 rounded-3xl bg-white shadow-sm border border-zinc-100 flex items-center justify-center mx-auto mb-8">
                <CheckCircle2 className="h-10 w-10 text-zinc-100" />
              </div>
              <h3 className="font-black text-2xl text-zinc-900 tracking-tight">All caught up!</h3>
              <p className="mt-2 text-sm font-medium text-zinc-400 max-w-[280px] mx-auto">No {filter} tasks remaining. You're operating at peak efficiency.</p>
              <Button className="mt-10 h-12 px-10 rounded-2xl bg-zinc-900 text-[10px] font-black uppercase tracking-[0.2em] text-white hover:bg-zinc-800">Create Task</Button>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}
